name: 'flights_dbt'
version: '1.0'
config-version: 2

profile: 'airflow_dbt'

target-path: "target"
clean-targets:
  - "target"

models:
  flights_dbt:
    staging:
      materialized: view
    transform:
      materialized: view
    marts:
      materialized: table
    tests:
      materialized: ephemeral
