version: '3.9'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
    - .env
  volumes:
    - ./etl:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:14.0
    container_name: postgres_airflow
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init_script:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  webserver:
    <<: *airflow-common
    command: ["bash", "-c", "airflow db init && airflow webserver"]
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: ["bash", "-c", "airflow db migrate && airflow users create --username admin --firstname Jakub --lastname Grabarczyk --role Admin --email kubagrabarczyk98@gmail.com --password admin && airflow scheduler"]
