version: '3.9'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
#  image: apache/airflow:2.10.4
  env_file:
    - airflow.env
    - .env
  volumes:
    - ./etl:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./dbt:/opt/airflow/dbt
  depends_on:
    - postgres
  networks:
    - airflow_network

services:
  postgres:
    image: postgres:14.0
    container_name: postgres_airflow
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init_script:/docker-entrypoint-initdb.d
    networks:
      - airflow_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - airflow_network

  webserver:
    <<: *airflow-common
    command: ["bash", "-c", "airflow db init && airflow webserver"]
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: ["bash", "-c", "airflow db migrate && airflow users create --username admin --firstname Jakub --lastname Grabarczyk --role Admin --email kubagrabarczyk98@gmail.com --password admin && airflow scheduler"]

#  dbt:
#    image: ghcr.io/dbt-labs/dbt-postgres:latest
#    container_name: dbt_container
#    depends_on:
#      - postgres
#    volumes:
#      - ./dbt:/dbt
#    working_dir: /dbt
#    environment:
#      DBT_PROFILES_DIR: /dbt
#    networks:
#      - airflow_network
#    entrypoint: ["tail", "-f", "/dev/null"]

networks:
  airflow_network:
    driver: bridge
